2024-08-12 09:24:12,090 11168 INFO ? odoo: Odoo version 15.0-20240717 
2024-08-12 09:24:12,090 11168 INFO ? odoo: Using configuration file at D:\Odoo15\conf\odoo.conf 
2024-08-12 09:24:12,090 11168 INFO ? odoo: addons paths: ['D:\\Odoo15\\server\\odoo\\addons', 'c:\\users\\cjnst\\appdata\\local\\openerp s.a\\odoo\\addons\\15.0', 'd:\\odoo15\\server\\odoo\\addons', 'd:\\odoo15\\custom_addons'] 
2024-08-12 09:24:12,091 11168 INFO ? odoo: database: odoo15@localhost:5432 
2024-08-12 09:24:12,208 11168 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at D:\Odoo15\thirdparty\wkhtmltopdf.exe 
2024-08-12 09:24:12,427 11168 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-GN9VHO1F:8015 
2024-08-12 09:24:28,074 7640 INFO OdooTest odoo.modules.loading: loading 1 modules... 
2024-08-12 09:24:28,079 7640 INFO OdooTest odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2024-08-12 09:24:28,096 7640 INFO OdooTest odoo.modules.loading: loading 43 modules... 
2024-08-12 09:24:28,097 7640 WARNING OdooTest odoo.modules.loading: Transient module states were reset 
2024-08-12 09:24:28,098 7640 ERROR OdooTest odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
                 ^^^^^^^^^^^^^^^^^^^^
TypeError: type.__new__() argument 1 must be str, not tuple
2024-08-12 09:24:28,101 7640 INFO OdooTest werkzeug: 127.0.0.1 - - [12/Aug/2024 09:24:28] "[35m[1mGET / HTTP/1.1[0m" 500 - 12 0.005 0.060
2024-08-12 09:24:28,107 7640 ERROR OdooTest werkzeug: Error on request:
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "D:\Odoo15\server\odoo\service\server.py", line 482, in app
    return self.app(e, s)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 112, in application
    return application_unproxied(environ, start_response)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 87, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1355, in __call__
    return self.dispatch(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1321, in __call__
    return self.app(environ, start_wrapped)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\middleware\shared_data.py", line 287, in __call__
    return self.app(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1530, in dispatch
    odoo.registry(db).check_signaling()
  File "D:\Odoo15\server\odoo\__init__.py", line 125, in registry
    return modules.registry.Registry(database_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 63, in __new__
    return cls.new(db_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
TypeError: type.__new__() argument 1 must be str, not tuple - - -
2024-08-12 09:24:28,334 7640 INFO OdooTest odoo.modules.loading: loading 1 modules... 
2024-08-12 09:24:28,345 7640 INFO OdooTest odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2024-08-12 09:24:28,361 7640 INFO OdooTest odoo.modules.loading: loading 43 modules... 
2024-08-12 09:24:28,362 7640 WARNING OdooTest odoo.modules.loading: Transient module states were reset 
2024-08-12 09:24:28,363 7640 ERROR OdooTest odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
                 ^^^^^^^^^^^^^^^^^^^^
TypeError: type.__new__() argument 1 must be str, not tuple
2024-08-12 09:24:28,366 7640 INFO OdooTest werkzeug: 127.0.0.1 - - [12/Aug/2024 09:24:28] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 - 12 0.008 0.067
2024-08-12 09:24:28,369 7640 ERROR OdooTest werkzeug: Error on request:
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "D:\Odoo15\server\odoo\service\server.py", line 482, in app
    return self.app(e, s)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 112, in application
    return application_unproxied(environ, start_response)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 87, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1355, in __call__
    return self.dispatch(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1321, in __call__
    return self.app(environ, start_wrapped)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\middleware\shared_data.py", line 287, in __call__
    return self.app(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1530, in dispatch
    odoo.registry(db).check_signaling()
  File "D:\Odoo15\server\odoo\__init__.py", line 125, in registry
    return modules.registry.Registry(database_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 63, in __new__
    return cls.new(db_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
TypeError: type.__new__() argument 1 must be str, not tuple - - -
2024-08-12 09:26:12,625 7640 INFO OdooTest odoo.modules.loading: loading 1 modules... 
2024-08-12 09:26:12,629 7640 INFO OdooTest odoo.modules.loading: 1 modules loaded in 0.00s, 0 queries (+0 extra) 
2024-08-12 09:26:12,645 7640 INFO OdooTest odoo.modules.loading: loading 43 modules... 
2024-08-12 09:26:12,646 7640 WARNING OdooTest odoo.modules.loading: Transient module states were reset 
2024-08-12 09:26:12,646 7640 ERROR OdooTest odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
                 ^^^^^^^^^^^^^^^^^^^^
TypeError: type.__new__() argument 1 must be str, not tuple
2024-08-12 09:26:12,649 7640 INFO OdooTest werkzeug: 127.0.0.1 - - [12/Aug/2024 09:26:12] "[35m[1mGET / HTTP/1.1[0m" 500 - 12 0.005 0.054
2024-08-12 09:26:12,653 7640 ERROR OdooTest werkzeug: Error on request:
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "D:\Odoo15\server\odoo\service\server.py", line 482, in app
    return self.app(e, s)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 112, in application
    return application_unproxied(environ, start_response)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 87, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1355, in __call__
    return self.dispatch(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1321, in __call__
    return self.app(environ, start_wrapped)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\middleware\shared_data.py", line 287, in __call__
    return self.app(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1530, in dispatch
    odoo.registry(db).check_signaling()
  File "D:\Odoo15\server\odoo\__init__.py", line 125, in registry
    return modules.registry.Registry(database_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 63, in __new__
    return cls.new(db_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
TypeError: type.__new__() argument 1 must be str, not tuple - - -
2024-08-12 09:26:12,897 7640 INFO OdooTest odoo.modules.loading: loading 1 modules... 
2024-08-12 09:26:12,903 7640 INFO OdooTest odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2024-08-12 09:26:12,920 7640 INFO OdooTest odoo.modules.loading: loading 43 modules... 
2024-08-12 09:26:12,921 7640 WARNING OdooTest odoo.modules.loading: Transient module states were reset 
2024-08-12 09:26:12,921 7640 ERROR OdooTest odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
                 ^^^^^^^^^^^^^^^^^^^^
TypeError: type.__new__() argument 1 must be str, not tuple
2024-08-12 09:26:12,924 7640 INFO OdooTest werkzeug: 127.0.0.1 - - [12/Aug/2024 09:26:12] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 - 12 0.009 0.072
2024-08-12 09:26:12,927 7640 ERROR OdooTest werkzeug: Error on request:
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "D:\Odoo15\server\odoo\service\server.py", line 482, in app
    return self.app(e, s)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 112, in application
    return application_unproxied(environ, start_response)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 87, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1355, in __call__
    return self.dispatch(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1321, in __call__
    return self.app(environ, start_wrapped)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\middleware\shared_data.py", line 287, in __call__
    return self.app(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1530, in dispatch
    odoo.registry(db).check_signaling()
  File "D:\Odoo15\server\odoo\__init__.py", line 125, in registry
    return modules.registry.Registry(database_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 63, in __new__
    return cls.new(db_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
TypeError: type.__new__() argument 1 must be str, not tuple - - -
2024-08-12 09:26:21,723 11168 INFO ? odoo.service.server: Initiating shutdown 
2024-08-12 09:26:21,723 11168 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2024-08-12 09:26:22,130 11168 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 2 connections  
2024-08-12 09:26:23,168 3068 INFO ? odoo: Odoo version 15.0-20240717 
2024-08-12 09:26:23,168 3068 INFO ? odoo: Using configuration file at D:\Odoo15\conf\odoo.conf 
2024-08-12 09:26:23,168 3068 INFO ? odoo: addons paths: ['D:\\Odoo15\\server\\odoo\\addons', 'c:\\users\\cjnst\\appdata\\local\\openerp s.a\\odoo\\addons\\15.0', 'd:\\odoo15\\server\\odoo\\addons', 'd:\\odoo15\\custom_addons'] 
2024-08-12 09:26:23,168 3068 INFO ? odoo: database: odoo15@localhost:5432 
2024-08-12 09:26:23,281 3068 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at D:\Odoo15\thirdparty\wkhtmltopdf.exe 
2024-08-12 09:26:23,460 3068 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-GN9VHO1F:8015 
2024-08-12 09:26:23,956 3068 INFO ? odoo.service.server: Initiating shutdown 
2024-08-12 09:26:23,956 3068 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2024-08-12 09:26:23,978 3068 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 2 connections  
2024-08-12 09:26:29,081 5204 INFO ? odoo: Odoo version 15.0-20240717 
2024-08-12 09:26:29,082 5204 INFO ? odoo: Using configuration file at D:\Odoo15\conf\odoo.conf 
2024-08-12 09:26:29,082 5204 INFO ? odoo: addons paths: ['D:\\Odoo15\\server\\odoo\\addons', 'c:\\users\\cjnst\\appdata\\local\\openerp s.a\\odoo\\addons\\15.0', 'd:\\odoo15\\server\\odoo\\addons', 'd:\\odoo15\\custom_addons'] 
2024-08-12 09:26:29,082 5204 INFO ? odoo: database: odoo15@localhost:5432 
2024-08-12 09:26:29,198 5204 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at D:\Odoo15\thirdparty\wkhtmltopdf.exe 
2024-08-12 09:26:29,382 5204 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-GN9VHO1F:8015 
2024-08-12 09:26:30,441 5204 INFO ? odoo.service.server: Initiating shutdown 
2024-08-12 09:26:30,441 5204 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2024-08-12 09:26:30,909 5204 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 2 connections  
2024-08-12 09:26:33,870 4748 INFO ? odoo: Odoo version 15.0-20240717 
2024-08-12 09:26:33,870 4748 INFO ? odoo: Using configuration file at D:\Odoo15\conf\odoo.conf 
2024-08-12 09:26:33,870 4748 INFO ? odoo: addons paths: ['D:\\Odoo15\\server\\odoo\\addons', 'c:\\users\\cjnst\\appdata\\local\\openerp s.a\\odoo\\addons\\15.0', 'd:\\odoo15\\server\\odoo\\addons', 'd:\\odoo15\\custom_addons'] 
2024-08-12 09:26:33,870 4748 INFO ? odoo: database: odoo15@localhost:5432 
2024-08-12 09:26:34,117 4748 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at D:\Odoo15\thirdparty\wkhtmltopdf.exe 
2024-08-12 09:26:40,457 11336 INFO ? odoo: Odoo version 15.0-20240717 
2024-08-12 09:26:40,457 11336 INFO ? odoo: Using configuration file at D:\Odoo15\conf\odoo.conf 
2024-08-12 09:26:40,457 11336 INFO ? odoo: addons paths: ['D:\\Odoo15\\server\\odoo\\addons', 'c:\\users\\cjnst\\appdata\\local\\openerp s.a\\odoo\\addons\\15.0', 'd:\\odoo15\\server\\odoo\\addons', 'd:\\odoo15\\custom_addons'] 
2024-08-12 09:26:40,457 11336 INFO ? odoo: database: odoo15@localhost:5432 
2024-08-12 09:26:40,663 11336 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at D:\Odoo15\thirdparty\wkhtmltopdf.exe 
2024-08-12 09:26:40,984 11336 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-GN9VHO1F:8015 
2024-08-12 09:27:33,436 11336 INFO ? odoo.service.server: Initiating shutdown 
2024-08-12 09:27:33,436 11336 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2024-08-12 09:27:33,679 11336 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 2 connections  
2024-08-12 09:27:49,838 12048 INFO ? odoo: Odoo version 15.0-20240717 
2024-08-12 09:27:49,838 12048 INFO ? odoo: Using configuration file at D:\Odoo15\conf\odoo.conf 
2024-08-12 09:27:49,838 12048 INFO ? odoo: addons paths: ['D:\\Odoo15\\server\\odoo\\addons', 'c:\\users\\cjnst\\appdata\\local\\openerp s.a\\odoo\\addons\\15.0', 'd:\\odoo15\\server\\odoo\\addons', 'd:\\odoo15\\custom_addons'] 
2024-08-12 09:27:49,838 12048 INFO ? odoo: database: odoo15@localhost:5432 
2024-08-12 09:27:49,957 12048 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at D:\Odoo15\thirdparty\wkhtmltopdf.exe 
2024-08-12 09:27:50,148 12048 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-GN9VHO1F:8015 
2024-08-12 09:27:52,221 7640 INFO OdooTest odoo.modules.loading: loading 1 modules... 
2024-08-12 09:27:52,230 7640 INFO OdooTest odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2024-08-12 09:27:52,253 7640 INFO OdooTest odoo.modules.loading: loading 43 modules... 
2024-08-12 09:27:52,255 7640 WARNING OdooTest odoo.modules.loading: Transient module states were reset 
2024-08-12 09:27:52,255 7640 ERROR OdooTest odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
                 ^^^^^^^^^^^^^^^^^^^^
TypeError: type.__new__() argument 1 must be str, not tuple
2024-08-12 09:27:52,260 7640 INFO OdooTest werkzeug: 127.0.0.1 - - [12/Aug/2024 09:27:52] "[35m[1mGET / HTTP/1.1[0m" 500 - 12 0.009 0.078
2024-08-12 09:27:52,270 7640 ERROR OdooTest werkzeug: Error on request:
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "D:\Odoo15\server\odoo\service\server.py", line 482, in app
    return self.app(e, s)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 112, in application
    return application_unproxied(environ, start_response)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 87, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1355, in __call__
    return self.dispatch(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1321, in __call__
    return self.app(environ, start_wrapped)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\middleware\shared_data.py", line 287, in __call__
    return self.app(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1530, in dispatch
    odoo.registry(db).check_signaling()
  File "D:\Odoo15\server\odoo\__init__.py", line 125, in registry
    return modules.registry.Registry(database_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 63, in __new__
    return cls.new(db_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
TypeError: type.__new__() argument 1 must be str, not tuple - - -
2024-08-12 09:27:52,473 7640 INFO OdooTest odoo.modules.loading: loading 1 modules... 
2024-08-12 09:27:52,479 7640 INFO OdooTest odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2024-08-12 09:27:52,497 7640 INFO OdooTest odoo.modules.loading: loading 43 modules... 
2024-08-12 09:27:52,498 7640 WARNING OdooTest odoo.modules.loading: Transient module states were reset 
2024-08-12 09:27:52,499 7640 ERROR OdooTest odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
                 ^^^^^^^^^^^^^^^^^^^^
TypeError: type.__new__() argument 1 must be str, not tuple
2024-08-12 09:27:52,504 7640 INFO OdooTest werkzeug: 127.0.0.1 - - [12/Aug/2024 09:27:52] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 - 12 0.007 0.069
2024-08-12 09:27:52,512 7640 ERROR OdooTest werkzeug: Error on request:
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "D:\Odoo15\server\odoo\service\server.py", line 482, in app
    return self.app(e, s)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 112, in application
    return application_unproxied(environ, start_response)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 87, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1355, in __call__
    return self.dispatch(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1321, in __call__
    return self.app(environ, start_wrapped)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\middleware\shared_data.py", line 287, in __call__
    return self.app(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1530, in dispatch
    odoo.registry(db).check_signaling()
  File "D:\Odoo15\server\odoo\__init__.py", line 125, in registry
    return modules.registry.Registry(database_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 63, in __new__
    return cls.new(db_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
TypeError: type.__new__() argument 1 must be str, not tuple - - -
2024-08-12 09:29:03,964 17156 INFO ? odoo: Odoo version 15.0-20240717 
2024-08-12 09:29:03,965 17156 INFO ? odoo: Using configuration file at D:\Odoo15\server\odoo.conf 
2024-08-12 09:29:03,965 17156 INFO ? odoo: addons paths: ['D:\\Odoo15\\server\\odoo\\addons', 'c:\\users\\cjnst\\appdata\\local\\openerp s.a\\odoo\\addons\\15.0', 'd:\\odoo15\\server\\odoo\\addons', 'd:\\odoo15\\custom_addons'] 
2024-08-12 09:29:03,965 17156 INFO ? odoo: database: odoo15@localhost:5432 
2024-08-12 09:29:04,061 17156 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at D:\Odoo15\thirdparty\wkhtmltopdf.exe 
2024-08-12 09:29:04,209 17156 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-GN9VHO1F:8015 
2024-08-12 09:29:08,310 17156 INFO ? odoo.sql_db: Connection to the database failed 
2024-08-12 09:29:12,452 17156 INFO ? odoo.sql_db: Connection to the database failed 
2024-08-12 09:29:21,334 17156 INFO ? odoo.service.server: Initiating shutdown 
2024-08-12 09:29:21,334 17156 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2024-08-12 09:29:21,483 17156 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 0 connections  
2024-08-12 09:30:52,248 6816 INFO ? odoo: Odoo version 15.0-20240717 
2024-08-12 09:30:52,249 6816 INFO ? odoo: Using configuration file at D:\Odoo15\conf\odoo.conf 
2024-08-12 09:30:52,249 6816 INFO ? odoo: addons paths: ['D:\\Odoo15\\server\\odoo\\addons', 'c:\\users\\cjnst\\appdata\\local\\openerp s.a\\odoo\\addons\\15.0', 'd:\\odoo15\\server\\odoo\\addons', 'd:\\odoo15\\custom_addons'] 
2024-08-12 09:30:52,249 6816 INFO ? odoo: database: odoo15@localhost:5432 
2024-08-12 09:30:52,381 6816 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at D:\Odoo15\thirdparty\wkhtmltopdf.exe 
2024-08-12 09:30:52,576 6816 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-GN9VHO1F:8015 
2024-08-12 09:30:56,647 6816 INFO ? odoo.sql_db: Connection to the database failed 
2024-08-12 09:31:00,699 6816 INFO ? odoo.sql_db: Connection to the database failed 
2024-08-12 09:31:34,409 6816 INFO ? odoo.service.server: Initiating shutdown 
2024-08-12 09:31:34,409 6816 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2024-08-12 09:31:34,590 6816 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 0 connections  
2024-08-12 09:31:35,498 13008 INFO ? odoo: Odoo version 15.0-20240717 
2024-08-12 09:31:35,498 13008 INFO ? odoo: Using configuration file at D:\Odoo15\conf\odoo.conf 
2024-08-12 09:31:35,498 13008 INFO ? odoo: addons paths: ['D:\\Odoo15\\server\\odoo\\addons', 'c:\\users\\cjnst\\appdata\\local\\openerp s.a\\odoo\\addons\\15.0', 'd:\\odoo15\\server\\odoo\\addons', 'd:\\odoo15\\custom_addons'] 
2024-08-12 09:31:35,498 13008 INFO ? odoo: database: odoo15@localhost:5432 
2024-08-12 09:31:35,600 13008 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at D:\Odoo15\thirdparty\wkhtmltopdf.exe 
2024-08-12 09:31:35,774 13008 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-GN9VHO1F:8015 
2024-08-12 09:31:39,834 13008 INFO ? odoo.sql_db: Connection to the database failed 
2024-08-12 09:31:43,888 13008 INFO ? odoo.sql_db: Connection to the database failed 
2024-08-12 09:32:19,556 7796 INFO ? odoo: Odoo version 15.0-20240717 
2024-08-12 09:32:19,556 7796 INFO ? odoo: Using configuration file at D:\Odoo15\server\odoo.conf 
2024-08-12 09:32:19,556 7796 INFO ? odoo: addons paths: ['D:\\Odoo15\\server\\odoo\\addons', 'c:\\users\\cjnst\\appdata\\local\\openerp s.a\\odoo\\addons\\15.0', 'd:\\odoo15\\server\\odoo\\addons', 'd:\\odoo15\\custom_addons'] 
2024-08-12 09:32:19,556 7796 INFO ? odoo: database: odoo15@localhost:5432 
2024-08-12 09:32:19,657 7796 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at D:\Odoo15\thirdparty\wkhtmltopdf.exe 
2024-08-12 09:32:19,798 7796 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-GN9VHO1F:8015 
2024-08-12 09:32:23,861 7796 INFO ? odoo.sql_db: Connection to the database failed 
2024-08-12 09:32:27,938 7796 INFO ? odoo.sql_db: Connection to the database failed 
2024-08-12 09:32:33,516 13008 INFO ? odoo.service.server: Initiating shutdown 
2024-08-12 09:32:33,516 13008 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2024-08-12 09:32:33,869 13008 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 0 connections  
2024-08-12 09:32:34,956 17876 INFO ? odoo: Odoo version 15.0-20240717 
2024-08-12 09:32:34,956 17876 INFO ? odoo: Using configuration file at D:\Odoo15\conf\odoo.conf 
2024-08-12 09:32:34,957 17876 INFO ? odoo: addons paths: ['D:\\Odoo15\\server\\odoo\\addons', 'c:\\users\\cjnst\\appdata\\local\\openerp s.a\\odoo\\addons\\15.0', 'd:\\odoo15\\server\\odoo\\addons', 'd:\\odoo15\\custom_addons'] 
2024-08-12 09:32:34,957 17876 INFO ? odoo: database: odoo15@localhost:5432 
2024-08-12 09:32:35,104 17876 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at D:\Odoo15\thirdparty\wkhtmltopdf.exe 
2024-08-12 09:32:35,290 17876 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-GN9VHO1F:8015 
2024-08-12 09:32:39,368 17876 INFO ? odoo.sql_db: Connection to the database failed 
2024-08-12 09:32:43,409 17876 INFO ? odoo.sql_db: Connection to the database failed 
2024-08-12 09:34:46,513 17876 INFO ? odoo.service.server: Initiating shutdown 
2024-08-12 09:34:46,513 17876 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2024-08-12 09:34:46,790 17876 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 0 connections  
2024-08-12 09:34:47,819 9108 INFO ? odoo: Odoo version 15.0-20240717 
2024-08-12 09:34:47,819 9108 INFO ? odoo: Using configuration file at D:\Odoo15\conf\odoo.conf 
2024-08-12 09:34:47,819 9108 INFO ? odoo: addons paths: ['D:\\Odoo15\\server\\odoo\\addons', 'c:\\users\\cjnst\\appdata\\local\\openerp s.a\\odoo\\addons\\15.0', 'd:\\odoo15\\server\\odoo\\addons', 'd:\\odoo15\\custom_addons'] 
2024-08-12 09:34:47,819 9108 INFO ? odoo: database: odoo15@localhost:5432 
2024-08-12 09:34:47,929 9108 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at D:\Odoo15\thirdparty\wkhtmltopdf.exe 
2024-08-12 09:34:48,131 9108 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-GN9VHO1F:8015 
2024-08-12 09:34:52,460 7796 INFO ? odoo.http: HTTP Configuring static files 
2024-08-12 09:34:52,537 7796 INFO OdooTest odoo.modules.loading: loading 1 modules... 
2024-08-12 09:34:52,585 7796 INFO OdooTest odoo.modules.loading: 1 modules loaded in 0.05s, 0 queries (+0 extra) 
2024-08-12 09:34:52,634 7796 INFO OdooTest odoo.modules.loading: loading 43 modules... 
2024-08-12 09:34:52,651 7796 WARNING OdooTest odoo.modules.loading: Transient module states were reset 
2024-08-12 09:34:52,652 7796 ERROR OdooTest odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
                 ^^^^^^^^^^^^^^^^^^^^
TypeError: type.__new__() argument 1 must be str, not tuple
2024-08-12 09:34:52,669 7796 INFO OdooTest werkzeug: 127.0.0.1 - - [12/Aug/2024 09:34:52] "[35m[1mGET / HTTP/1.1[0m" 500 - 11 0.021 0.172
2024-08-12 09:34:52,683 7796 ERROR OdooTest werkzeug: Error on request:
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "D:\Odoo15\server\odoo\service\server.py", line 482, in app
    return self.app(e, s)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 112, in application
    return application_unproxied(environ, start_response)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 87, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1355, in __call__
    return self.dispatch(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1321, in __call__
    return self.app(environ, start_wrapped)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\middleware\shared_data.py", line 287, in __call__
    return self.app(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1530, in dispatch
    odoo.registry(db).check_signaling()
  File "D:\Odoo15\server\odoo\__init__.py", line 125, in registry
    return modules.registry.Registry(database_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 63, in __new__
    return cls.new(db_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
TypeError: type.__new__() argument 1 must be str, not tuple - - -
2024-08-12 09:34:52,696 7796 INFO OdooTest odoo.modules.loading: loading 1 modules... 
2024-08-12 09:34:52,708 7796 INFO OdooTest odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2024-08-12 09:34:52,751 7796 INFO OdooTest odoo.modules.loading: loading 43 modules... 
2024-08-12 09:34:52,753 7796 WARNING OdooTest odoo.modules.loading: Transient module states were reset 
2024-08-12 09:34:52,753 7796 ERROR OdooTest odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
                 ^^^^^^^^^^^^^^^^^^^^
TypeError: type.__new__() argument 1 must be str, not tuple
2024-08-12 09:34:52,757 7796 INFO OdooTest werkzeug: 127.0.0.1 - - [12/Aug/2024 09:34:52] "[35m[1mGET / HTTP/1.1[0m" 500 - 11 0.009 0.063
2024-08-12 09:34:52,772 7796 ERROR OdooTest werkzeug: Error on request:
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "D:\Odoo15\server\odoo\service\server.py", line 482, in app
    return self.app(e, s)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 112, in application
    return application_unproxied(environ, start_response)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 87, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1355, in __call__
    return self.dispatch(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1321, in __call__
    return self.app(environ, start_wrapped)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\middleware\shared_data.py", line 287, in __call__
    return self.app(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1530, in dispatch
    odoo.registry(db).check_signaling()
  File "D:\Odoo15\server\odoo\__init__.py", line 125, in registry
    return modules.registry.Registry(database_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 63, in __new__
    return cls.new(db_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
TypeError: type.__new__() argument 1 must be str, not tuple - - -
2024-08-12 09:34:52,993 7796 INFO OdooTest odoo.modules.loading: loading 1 modules... 
2024-08-12 09:34:53,001 7796 INFO OdooTest odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2024-08-12 09:34:53,030 7796 INFO OdooTest odoo.modules.loading: loading 43 modules... 
2024-08-12 09:34:53,030 7796 WARNING OdooTest odoo.modules.loading: Transient module states were reset 
2024-08-12 09:34:53,032 7796 ERROR OdooTest odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
                 ^^^^^^^^^^^^^^^^^^^^
TypeError: type.__new__() argument 1 must be str, not tuple
2024-08-12 09:34:53,038 7796 INFO OdooTest werkzeug: 127.0.0.1 - - [12/Aug/2024 09:34:53] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 - 11 0.007 0.046
2024-08-12 09:34:53,045 7796 ERROR OdooTest werkzeug: Error on request:
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "D:\Odoo15\server\odoo\service\server.py", line 482, in app
    return self.app(e, s)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 112, in application
    return application_unproxied(environ, start_response)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 87, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1355, in __call__
    return self.dispatch(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1321, in __call__
    return self.app(environ, start_wrapped)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\middleware\shared_data.py", line 287, in __call__
    return self.app(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1530, in dispatch
    odoo.registry(db).check_signaling()
  File "D:\Odoo15\server\odoo\__init__.py", line 125, in registry
    return modules.registry.Registry(database_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 63, in __new__
    return cls.new(db_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
TypeError: type.__new__() argument 1 must be str, not tuple - - -
2024-08-12 09:37:06,675 9108 INFO ? odoo.service.server: Initiating shutdown 
2024-08-12 09:37:06,675 9108 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2024-08-12 09:37:06,694 9108 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 2 connections  
2024-08-12 09:37:07,799 12084 INFO ? odoo: Odoo version 15.0-20240717 
2024-08-12 09:37:07,799 12084 INFO ? odoo: Using configuration file at D:\Odoo15\conf\odoo.conf 
2024-08-12 09:37:07,800 12084 INFO ? odoo: addons paths: ['D:\\Odoo15\\server\\odoo\\addons', 'c:\\users\\cjnst\\appdata\\local\\openerp s.a\\odoo\\addons\\15.0', 'd:\\odoo15\\server\\odoo\\addons', 'd:\\odoo15\\custom_addons'] 
2024-08-12 09:37:07,800 12084 INFO ? odoo: database: odoo15@localhost:5432 
2024-08-12 09:37:07,956 12084 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at D:\Odoo15\thirdparty\wkhtmltopdf.exe 
2024-08-12 09:37:08,170 12084 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-GN9VHO1F:8015 
2024-08-12 09:37:09,556 7796 INFO OdooTest odoo.modules.loading: loading 1 modules... 
2024-08-12 09:37:09,567 7796 INFO OdooTest odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2024-08-12 09:37:09,600 7796 INFO OdooTest odoo.modules.loading: loading 43 modules... 
2024-08-12 09:37:09,602 7796 WARNING OdooTest odoo.modules.loading: Transient module states were reset 
2024-08-12 09:37:09,602 7796 ERROR OdooTest odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
                 ^^^^^^^^^^^^^^^^^^^^
TypeError: type.__new__() argument 1 must be str, not tuple
2024-08-12 09:37:09,607 7796 INFO OdooTest werkzeug: 127.0.0.1 - - [12/Aug/2024 09:37:09] "[35m[1mGET / HTTP/1.1[0m" 500 - 11 0.008 0.054
2024-08-12 09:37:09,614 7796 ERROR OdooTest werkzeug: Error on request:
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "D:\Odoo15\server\odoo\service\server.py", line 482, in app
    return self.app(e, s)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 112, in application
    return application_unproxied(environ, start_response)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 87, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1355, in __call__
    return self.dispatch(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1321, in __call__
    return self.app(environ, start_wrapped)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\middleware\shared_data.py", line 287, in __call__
    return self.app(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1530, in dispatch
    odoo.registry(db).check_signaling()
  File "D:\Odoo15\server\odoo\__init__.py", line 125, in registry
    return modules.registry.Registry(database_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 63, in __new__
    return cls.new(db_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
TypeError: type.__new__() argument 1 must be str, not tuple - - -
2024-08-12 09:37:09,661 7796 INFO OdooTest odoo.modules.loading: loading 1 modules... 
2024-08-12 09:37:09,666 7796 INFO OdooTest odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2024-08-12 09:37:09,684 7796 INFO OdooTest odoo.modules.loading: loading 43 modules... 
2024-08-12 09:37:09,685 7796 WARNING OdooTest odoo.modules.loading: Transient module states were reset 
2024-08-12 09:37:09,685 7796 ERROR OdooTest odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
                 ^^^^^^^^^^^^^^^^^^^^
TypeError: type.__new__() argument 1 must be str, not tuple
2024-08-12 09:37:09,688 7796 INFO OdooTest werkzeug: 127.0.0.1 - - [12/Aug/2024 09:37:09] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 - 11 0.004 0.028
2024-08-12 09:37:09,691 7796 ERROR OdooTest werkzeug: Error on request:
Traceback (most recent call last):
  File "D:\Odoo15\server\odoo\modules\registry.py", line 61, in __new__
    return cls.registries[db_name]
  File "D:\Odoo15\server\odoo\tools\func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Odoo15\server\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'OdooTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "D:\Odoo15\server\odoo\service\server.py", line 482, in app
    return self.app(e, s)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 112, in application
    return application_unproxied(environ, start_response)
  File "D:\Odoo15\server\odoo\service\wsgi_server.py", line 87, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1355, in __call__
    return self.dispatch(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1321, in __call__
    return self.app(environ, start_wrapped)
  File "D:\Odoo15\python\Lib\site-packages\werkzeug\middleware\shared_data.py", line 287, in __call__
    return self.app(environ, start_response)
  File "D:\Odoo15\server\odoo\http.py", line 1530, in dispatch
    odoo.registry(db).check_signaling()
  File "D:\Odoo15\server\odoo\__init__.py", line 125, in registry
    return modules.registry.Registry(database_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 63, in __new__
    return cls.new(db_name)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\Odoo15\server\odoo\modules\loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "D:\Odoo15\server\odoo\modules\loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "D:\Odoo15\server\odoo\modules\loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
  File "D:\Odoo15\server\odoo\modules\registry.py", line 237, in load
    model = cls._build_model(self, cr)
  File "D:\Odoo15\server\odoo\models.py", line 628, in _build_model
    ModelClass = type(name, (cls,), {
TypeError: type.__new__() argument 1 must be str, not tuple - - -
2024-08-12 09:37:45,443 12084 INFO ? odoo.service.server: Initiating shutdown 
2024-08-12 09:37:45,444 12084 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2024-08-12 09:37:45,606 12084 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 2 connections  
2024-08-12 09:37:46,889 14376 INFO ? odoo: Odoo version 15.0-20240717 
2024-08-12 09:37:46,890 14376 INFO ? odoo: Using configuration file at D:\Odoo15\conf\odoo.conf 
2024-08-12 09:37:46,890 14376 INFO ? odoo: addons paths: ['D:\\Odoo15\\server\\odoo\\addons', 'c:\\users\\cjnst\\appdata\\local\\openerp s.a\\odoo\\addons\\15.0', 'd:\\odoo15\\server\\odoo\\addons', 'd:\\odoo15\\custom_addons'] 
2024-08-12 09:37:46,890 14376 INFO ? odoo: database: odoo15@localhost:5432 
2024-08-12 09:37:47,003 14376 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at D:\Odoo15\thirdparty\wkhtmltopdf.exe 
2024-08-12 09:37:47,177 14376 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-GN9VHO1F:8015 
2024-08-12 09:37:47,431 14376 INFO ? odoo.service.server: Initiating shutdown 
2024-08-12 09:37:47,431 14376 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2024-08-12 09:37:47,699 14376 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 2 connections  
